  language: python
  python:
    - "2.7"
    - "3.5"
    - "3.7"

  cache: packages

  sudo: required

  script:
    - cd python
    - pip install -U .[test]
    - python setup.py test

  after_success:
    - coveralls
