  language: python
  python:
    - "3.5"
    - "3.6"

  cache: packages

  sudo: required

  script:
    - cd python
    - pip install -U .[test]
    - python setup.py test

  after_success:
    - coveralls
